[package]
name = "ore-app"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.12.0"
bincode = "1.3.3"
cached = "0.47.0"
dioxus = "0.4.3"
dioxus-router = "0.4.3"
dioxus-std = { version = "0.4.1", features = ["clipboard", "utils"] }
dioxus-web = "0.4.3"
futures = "0.3.30"
gloo = "0.11.0"
gloo-storage = "0.3.0"
js-sys = "0.3.67"
log = "0.4.20"
ore = { package = "ore-program", version = "0.0.3", features = ["no-entrypoint"] }
ore-types = "0.0.1"
qrcode-generator = "4.1.9"
reqwest = "0.11.24"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6.3"
serde_json = "1.0"
solana-client-wasm = { version = "1.17.4", features = ["pubsub"] }
solana-extra-wasm = "1.17.4"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.41"
wasm-logger = "0.2.0"
web-time = "1.0.0"

[dependencies.web-sys]
version = "0.3"
features = [
    'console',
    'Clipboard',
    'Document',
    'HtmlElement',
    'HtmlInputElement',
    'MessageEvent',
    'Navigator',
    'Window',
    'Worker',
    'WorkerOptions',
    'WorkerType',
    'WorkerGlobalScope',
]

[patch.crates-io]
solana-client-wasm = { version = "1.17.4", git = "https://github.com/hardhatchad/solana-playground", branch = "master" }
solana-extra-wasm = { version = "1.17.4", git = "https://github.com/hardhatchad/solana-playground", branch = "master" }
